<div class="oag-blog-summary">
    <?= $block->getSummaryCmsBlockHtml(); ?>
</div>

<?php $postCollection =  $block->getPostCollection(); ?>
<?php if ($postCollection->getSize() > 0): ?>
    <div class="oag-blog-list">
        <ul class="post-list"><!--
            <?php foreach ($postCollection as $post): ?>
            --><li class="post-item"><?= $block->getPostHtml($post) ?></li><!--
            <?php endforeach; ?>
        --></ul>
    </div>
    <?= $block->getToolbarHtml() ?>
<?php else: ?>
    <div class="message info empty">
        <div>
            <?= $block->escapeHtml(__('There are no posts at this moment.')) ?>
        </div>
    </div>
<?php endif; ?>
