<?php
    $post = $block->getPost();
    $postUrl = $escaper->escapeUrl($post->getUrl());
    $postTitle = $escaper->escapeHtml($post->getTitle());
    $listImage = $post->getListImageUrl();
?>
<div class="post-item-wraper">
    <?php if ($listImage): ?>
        <div class="image-container">
            <a href="<?= $postUrl ?>" title="<?= $escaper->escapeHtml($post->getListImageAlt()); ?>">
                <div class="image-background" style="background-image: url(<?= $listImage ?>)"></div>
            </a>
        </div>
    <?php endif; ?>
    <div class="title">
        <h2><a href="<?= $postUrl ?>" title="<?= $postTitle; ?>">
            <?= $postTitle ?>
        </a></h2>
        <div class="publish-date">
            <?= $this->getPublishedAtHtml(); ?>
        </div>
    </div>
    <div class="short-content">
        <?= $post->getShortContent(); ?>
    </div>
    <div class="read-more">
        <a href="<?= $postUrl ?>" title="<?= __('Read more'); ?>">
            <?= __('Read more'); ?>
        </a>
    </div>
</div>